### ISSUE TITLE
Include version number into report and filename

### ISSUE THREAD

**Issue by fairking** [redskap/swagger-brake#107]
Hi everyone,

Is the any way to include the version number to the report and filename?

For example the following command:
```bash
java -jar "..\..\Utils\SwaggerBrake\swagger-brake-2.3.0-cli.jar" --old-api=schema_old.json --new-api=schema.json --output-formats=HTML --output-path=.\
```

Would generate the following file: `swagger-brake-1.0.1.html`. and the version also included into the document itself:
![image](https://github.com/redskap/swagger-brake/assets/13495631/5f6b9972-9612-4e6e-8106-a50ae2d8a9f5)

The version number is determined by the schema.json (see `info.version`)
```json
{
  "openapi": "3.0.1",
  "info": {
    "title": "My Project API",
    "description": "Ground breaking software",
    "version": "1.0.1"
  },
```

It would be also nice to customize the report filename as well (eg. `my-project-breaking-changes.html`).

Thanks.

**Comment by galovics** [comment]
Hi @fairking. Currently you can't customize the report and the name of the report file although it shouldn't be a big deal to implement those things.

Before we do that, would you mind explaining a bit your use-case?
Thanks

**Comment by galovics** [comment]
Noted, thanks @fairking for the explanation.

**Comment by galovics** [comment]
Will look like this:
![image](https://github.com/redskap/swagger-brake/assets/4701389/eb3b9b27-7d00-4f28-8f75-a6d50f668094)

**Comment by galovics** [comment]
Done in https://github.com/redskap/swagger-brake/pull/115
