### ISSUE TITLE
Can you provide a simple entrypoint to compare 2 API instances

### ISSUE THREAD

**Issue by dalewking** [redskap/swagger-brake#16]
Since you are splitting out the CLI from the core library, was hoping you could provide a simple entry point that takes in 2 OpenAPI instances and returns the list of breaking changes.

Here is the code I am currently doing on my side, but you could do it much easier in the library:

    private static Collection<BreakingChange> invokeSwaggerBrake(@NotNull OpenAPI oldApi, @NotNull OpenAPI newApi) {
        AnnotationConfigApplicationContext context = new AnnotationConfigApplicationContext(
                RunnerConfiguration.class, ReporterConfiguration.class,
                MavenConfiguration.class, CoreConfiguration.class);

        final String beanName = context.getBeanNamesForType(
                ResolvableType.forClassWithGenerics(Transformer.class, OpenAPI.class, Specification.class))[0];

        @SuppressWarnings("unchecked")
        final Transformer<OpenAPI, Specification> transformer
                = (Transformer<OpenAPI, Specification>)context.getBean(beanName);

        return context.getBean(BreakChecker.class).check(transformer.transform(oldApi), transformer.transform(newApi));
    }

Should be easy if you extract this expression on Runner to a new method called check:

    breakChecker.check(transformer.transform(oldApi), transformer.transform(newApi));

Extract everything before `.run(options)` in Starter.start to a getRunner method. Then add this method to Starter:

    public static Collection<BreakingChange> check(@NotNull OpenAPI oldApi, @NotNull OpenAPI newApi) {
        return getRunner().check(oldApi, newApi);
    }

**Comment by galovics** [comment]
Done. Please check if it suits your use-case. :-)

**Comment by dalewking** [comment]
I don't see how it is undermining modularity. You provide that with Starter.start. All I am asking for is Starter to look like this:

```
public class Starter {
    private static BeanFactory getBeanFactory() {
        return new AnnotationConfigApplicationContext(RunnerConfiguration.class, ReporterConfiguration.class,
                MavenConfiguration.class, CoreConfiguration.class);
    }

    public static Collection<BreakingChange> start(Options options) {
        return getBeanFactory().getBean(Runner.class).run(options);
    }

    public static Collection<BreakingChange> check(OpenAPI oldApi, OpenAPI newApi) {
        return getBeanFactory().getBean(Checker.class).check(oldApi, newApi);
    }
}
```

**Comment by galovics** [comment]
You got it @dalewking. :-)
