### ISSUE TITLE
Add ability to allow removal of deprecated APIs

### ISSUE THREAD

**Issue by dalewking** [redskap/swagger-brake#17]
Add ability to allow removal of an API previously marked as deprecated

**Comment by dalewking** [comment]
Thanks for adding this, but you probably should add a configuration option to enable this. Some people feel that APIs should never be deleted.

**Comment by galovics** [comment]
@dalewking thanks for reporting it first of all. :-)
The OpenAPI spec allows you to deprecate APIs using the deprecated attribute on operation level. See the spec here: https://swagger.io/specification/#fixed-fields-8

Swagger Brake will check for this flag. If the old API is marked as deprecated and it got removed in the new version of the API, it won't be considered a breaking change anymore.

**Comment by dalewking** [comment]
I know all of that but deprecation simply means that people should no longer use it. Actually deleting it is a breaking change and according to some (e.g. https://api-university.com/api-lifecycle/api-design/api-design-api-evolution-api-versioning/) you should never make breaking changes and would have trouble with this being the default. So it would be best to add an option to enable this behavior

**Comment by galovics** [comment]
From my point of view, if anyone deletes an API which is already marked as deprecated, it might get deleted without any problem. Of course if people doesn't give the necessary time for the clients to switch from API1 to API2, it might get messy. 
Although a switch might be useful just to have the possibility for changing this behavior. I'll add it and make the behavior default and one can override it to explicitly mark that deprecated API deletion is not allowed.
