### ISSUE TITLE
Allow configuring the filename scanned from maven

### ISSUE THREAD

**Issue by dalewking** [redskap/swagger-brake#18]
As the documentation says:

> The downloaded JAR will be scanned for any of the following files which will be used for providing the old API:
> 
> - swagger.json
> - swagger.yaml
> - swagger.yml

I don't want swagger used in the name, since my file is an open api file and I prefer to maintain the distinction between swagger and openApi. I am proposing a new config property to set the base name of the file to look for that defaults to "swagger". Swagger brake then looks for a file with that base name with the extension .json, .yaml, or .yml

**Comment by galovics** [comment]
@dalewking will be released in the next version.
