### ISSUE TITLE
Support for beta API

### ISSUE THREAD

**Issue by ChristianLutz** [redskap/swagger-brake#19]
Hello,

this is an idea for a feature request.

Let's assume I do have a stable 1.0 API. Now we would like to provide a new endpoint, but in the current state we are not sure if the new API will work properly. So we release the new API 1.1 and tell the user to play around. But now, if we have to change the API because of user feedback for version 1.2 swagger-brake will fail as expected. 

However If we could annotate the API as beta in the first place it would be possible to identify this API and ignore any breaking changes. 

The Problem is swagger doesn't support a beta tag yet. See [here](https://github.com/OAI/OpenAPI-Specification/issues/432). As metioned in the issue it is possible to add a [vendor extension](https://swagger.io/docs/specification/openapi-extensions/)

This could be something like:

    x-brake-beta: true
    x-brake-beta-api-name: uniqeXXX

I guess the `x-brake-beta-api-name` is required to ensure the same api's are compared. But I am not sure, maybe `x-brake-beta` is enough.

The following state could appear: 
      
              -> Beta API -> OK // added
     Beta API -> Beta API -> OK // changed
     Beta API -> API -> OK      // stable
     Beta API ->     -> OK      // removed
     API -> Beta API -> FAIL    // brake

kind regards
Christian

**Comment by galovics** [comment]
Hi @ChristianLutz, it's a good idea, although I would rather introduce a configuration parameter for the specific attribute which denotes the beta property of the API instead of hardcoding it. I'll take a look.

**Comment by galovics** [comment]
@ChristianLutz will be included in the next release. Thanks for the idea.

**Comment by galovics** [comment]
FYI @ChristianLutz here's the relevant part from the readme: https://github.com/redskap/swagger-brake#beta-api-support
