### ISSUE TITLE
Change in type of response attribute is not detected

### ISSUE THREAD

**Issue by MinniArora** [redskap/swagger-brake#24]
Changed response attribute id from integer to string, as below, and this failing change was not detected.

From:
"Pet": {
      "type": "object",
      "required": [
        "name",
        "photoUrls"
      ],
      "properties": {
        "id": {
          "type": "integer",
          "format": "int64"
        },
......

To:
"Pet": {
      "type": "object",
      "required": [
        "name",
        "photoUrls"
      ],
      "properties": {
        "id": {
          "type": "string"
        },
.............................

**Comment by galovics** [comment]
Thanks @MinniArora. Will be fixed in the next release.

**Comment by MinniArora** [comment]
Thank you for a quick fix
