### ISSUE TITLE
Add route path exclusion parameter support

### ISSUE THREAD

**Issue by omriarnon-s1** [redskap/swagger-brake#36]
Currently, we have some Private API's in our spec. They are being broken all the time, but it doesn't bother us.
However, the swagger-brake fails, of course, because it detects breaking changes in the API.

Is it possible to add a parameter for partial path (e.g --exclude-path /api/private) which will exclude these API's from the scan? or at least WARN about them, but not mark the check as 'Not backwards compatible'

**Comment by galovics** [comment]
@omriarnon-s1 good idea but can't you rely on using [Beta APIs](https://github.com/redskap/swagger-brake#beta-api-support)?

**Comment by galovics** [comment]
Implemented, will be released in 2.0.1
