### ISSUE TITLE
Need null checks for getContent

### ISSUE THREAD

**Issue by dalewking** [redskap/swagger-brake#6]
Had a Swagger 2.0 file that I converted to 3.0 and when ran with your tool would fail with null pointer exceptions. These occurred in ApiResponseTransformer and RequestBodyTransformer because getContent() returned null.

I think you need some null checking like this (version for ApiResponseTransformer):

       final Content content = from.getValue().getContent();
       Set<Map.Entry<String, MediaType>> entries = content != null ? content.entrySet() : Collections.emptySet();

When I added the null checks to those classes the check worked as expected

**Comment by galovics** [comment]
Thanks for reporting @dalewking. Could you please provide an example specification with which the issue is reproducible? Thanks!

**Comment by dalewking** [comment]
I am fine with providing it to you personally to investigate, but do not want to publish it publicly. I'll see if I can provide a sanitized stripped down simple example.

**Comment by dalewking** [comment]
So actually I could pair it down to just the acuator/info route that gets added to the project. It may not be actually valid OpenAPI:

```
openapi: 3.0.0
info:
  title: EXAMPLE
  version: '1'
paths:
  /actuator/info:
    get:
      tags:
        - operation-handler
      summary: handle
      operationId: handleUsingGET_1
      responses:
        '200':
          description: OK
          responseSchema:
            type: object
          content:
            application/json:
              schema:
                type: object
            application/vnd.spring-boot.actuator.v2+json:
              schema:
                type: object
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      deprecated: false
      requestBody:
        $ref: '#/components/requestBodies/handleUsingGETBody'
components:
  requestBodies:
    handleUsingGETBody:
      content:
        application/json:
          schema:
            type: object
            additionalProperties:
              type: string
      description: body

```

**Comment by dalewking** [comment]
I wonder if this case the issue is that you are not following the $ref to get the content

**Comment by dalewking** [comment]
Yes, that appears to be the problem. There is a content entry, but you have to follow the $ref to get to it.

**Comment by dalewking** [comment]
Since the issue is really that you are not supporting reference objects for anything other than Schema, I will close this and create a new issue for the real problem
