### ISSUE TITLE
Schema class attributeRequiredMap.get(attrToSearchFor); returning null

### ISSUE THREAD

**Issue by zaidsir** [redskap/swagger-brake#65]
Hello, I have a case where `attributeRequiredMap.get(attrToSearchFor);` is returning null in the Boolean `isRequired` like the following Image

![image](https://user-images.githubusercontent.com/2502050/174073258-18282c10-e2c0-498f-8037-cd5d454f9897.png)

I was wondering if the `isRequired` can be converted into a primitive boolean in order not to have NPE, the following is the content of the map

![image](https://user-images.githubusercontent.com/2502050/174073780-9a8fcee6-64fa-4a88-84e2-95185be82841.png)

Also current `attrToSearchFor` value is `urn:scim:schemas:extension:workspace:1` the closest value in the map is `urn:scim:schemas:extension:workspace:1.0` I suspect that is this something related to the construction of `attrToSearchFor` using the stringJoiner.

Thank you

**Comment by galovics** [comment]
Hi @zaidsir,
Thanks for reporting these issues. I'll take a look when I have the time unless you have a PR prepared. ;-)

**Comment by lavanya2290** [comment]
The same works in 2.2.0 verions It handles NPE. Like making use of Optional.ofNullable.
public Set<String> getRequiredAttributeNames() {
        Collection<SchemaAttribute> schemaAttrs = schemaAttributes;
        if (CollectionUtils.isEmpty(schemaAttrs)) {
            schemaAttrs = Optional.ofNullable(schema).map(Schema::getSchemaAttributes).orElse(Collections.emptySet());
        }
        return internalGetAttributeData(schemaAttrs, "", SchemaAttribute::isRequired)
            .stream()
            .filter(p -> BooleanUtils.isTrue(p.getRight()))
            .map(Pair::getLeft)
            .collect(toSet());
    }
versus new method in 2.3.0 causes issues i.e. NPE.
Example we can have a variable annotated with 
    public static final String SCHEMA = "urn:abc:def:abc:abc:1.0";

**Comment by zaidsir** [comment]
Hello @galovics, a simple pull request created. Please review it

**Comment by galovics** [comment]
Just for reference, the PR is here: https://github.com/redskap/swagger-brake/pull/66

**Comment by galovics** [comment]
@zaidsir the other issue, with the complex dotted attribute name is fixed with this PR: https://github.com/redskap/swagger-brake/pull/84
