### ISSUE TITLE
Swagger brake cli jar in maven repository 

### ISSUE THREAD

**Issue by gituserjava** [redskap/swagger-brake#96]
I downloaded swagger brake cli from maven repository but it is not bundled with the dependencies and hence when I run the cli it is failing. I size of latest version on GitHub page is 27+MB on /releases whereas it is 17KB on Maven repository.We are not allowed to download from /releases and are allowed only to download from Maven repository. Please let us know how we can get the swagger brake jar that is bundled with all the dependencies into it from maven repository?

**Comment by galovics** [comment]
Done.
